### ISSUE TITLE
Cannot invert gyro Y axis

### ISSUE THREAD

**Issue by lyahdav** [Electronicks/JoyShockMapper#30] opened 2021-07-25 19:14 UTC
I'm trying to use JoyShockMapper in Xbox Cloud gaming (running in Chrome on Windows 10) with a Nintendo Switch Pro controller so that I can use the gyro to control the right stick for better aiming in FPS games. I have it working by using https://github.com/ViGEm/ViGEmBus and https://github.com/ViGEm/HidHide and using the follow config:
```
VIRTUAL_CONTROLLER = XBOX

UP = X_UP
DOWN = X_DOWN
LEFT = X_LEFT
RIGHT = X_RIGHT
L = X_LB
R = X_RB
W = X_X
S = X_A
N = X_Y
E = X_B
L3 = X_LS
R3 = X_RS
- = X_BACK
+ = X_START
HOME = X_GUIDE
ZL_MODE = X_LT
ZR_MODE = X_RT
LEFT_STICK_MODE = LEFT_STICK
RIGHT_STICK_MODE = RIGHT_STICK
MOTION_STICK_MODE = RIGHT_STICK
```

But the Gyro Y axis is inverted so that up moves my gun down and vice-versa. I tried fixing with the following but it doesn't work:
```
GYRO_AXIS_Y = INVERTED
```

**Comment by Electronicks** [comment] 2021-07-28 16:03
Fixed in v3.2.2

**Comment by lyahdav** [comment] 2021-07-30 05:16
I just tried building from source master branch and I still repro this with the steps in the OP. I also didn't see in the v3.2.2 commit any changes that would seem to fix this.

**Comment by Electronicks** [comment] 2021-07-30 14:03
My bad. I thought it was a duplicate of #25

**Comment by Electronicks** [comment] 2021-07-30 23:09
So, the settings STICK_AXIS_[X|Y] is the one used to invert the motion stick, unfortunately this will also inverse all the other sticks, which is a significant problem. I'll come up with a solution for this.

**Comment by Electronicks** [comment] 2021-08-13 16:56
See new settings in v3.2.3

**Closed by Electronicks** 2021-08-13 16:56 UTC
